---
- name: Install Apache HTTP web server
  yum:
          name=httpd
          state=latest


- name: Start Apache web server
  service:
          name=httpd
          state=started
          enabled=yes
- name: get ip address
  debug: msg={{ ansible_ens32.ipv4.address }}
- name: Copy files to webserver
  copy: src=icons8-developer-64.png dest=/var/www/html/icons8-developer-64.png

- name: Deploy website on server
  template: src=index.html.j2 dest=/var/www/html/index.html

  notify: restart apache

- name: Configure FirewallD to Allow HTTP Connections
  firewalld: 
   service=http
   permanent=true
   state=enabled
   immediate=yes

  notify: restart firewalld

- name: Configure FirewallD to Allow HTTPs Connections
  firewalld: 
   service=https
   permanent=true
   state=enabled
   immediate=yes

  notify: restart firewalld
